# datasource
spring.datasource.dynamic:
  primary: core
  strict: true
  datasource:
    core:
      url: jdbc:h2:mem:pooi-workflow-core;DB_CLOSE_DELAY=-1;MODE=MySQL
      username: sa
      password:
      init:
        schema: classpath*:sql/tenant_ddl.sql
        data: classpath*:sql/h2_tenant_dml.sql